- name: Include accounts
  include_vars:
    file:  ../../account_domain.yml
    name: accounts
  tags: common

- name: Include domain configuration file
  include_vars:
    file: ../../domain-config.yml
    name: domain
  tags: common

- name: set domain controller IP
  set_fact:
    domain_controller_ips: "{{ lookup('flattened', groups['domain_controllers'] | map('extract', hostvars, ['private_ipv4_addresses']) | list) }}"
#    ansible_user: "{{ accounts.localadmin.username }}"
#   ansible_password: "{{ accounts.localadmin.password }}"
  tags: common

# Needs to be performed after the set_fact block which sets up the remote user and password to use
- name: Gather remote facts
  setup: {}
  tags: common

- name: Set domain controllers as DNS servers
  ansible.windows.win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ domain_controller_ips }}"

- name: Ensure workstation is domain-joined
  microsoft.ad.membership:
    dns_domain_name: "{{ domain.dns_name }}"
    hostname: "{{ ansible_env.COMPUTERNAME }}"
    domain_admin_user: "{{ accounts.domadmin.username }}@{{ domain.dns_name }}"
    domain_admin_password: "{{ accounts.domadmin.password }}"
    state: domain
    reboot: true
  register: domain_state

#- name: Reboot machine if it has just joined the domain
#  win_reboot: {}
#  when: domain_state.reboot_required

- name: Ensure domain users can RDP on any workstation
  ansible.windows.win_group_membership:
    name: Remote Desktop Users
    members: "{{ accounts.domusers | map(attribute='username') | list }}"
  # Note: currently, local users cannot be set as local admins from the YAML configuration

- name: Read local users list from domain configuration file
  set_fact:
    local_users: "{{ domain.workstations | selectattr('name', 'equalto', ansible_env.COMPUTERNAME) | map(attribute='local_users') | reject('undefined') | select() | list }}"

- name: Ensure local users are created
  ansible.windows.win_user:
    name: "{{ item.username is defined | ternary(item.username, item) }}"
    password: "{{ item.password is defined | ternary(item.password, item) }}"
  with_items: "{{ local_users }}"
  when: local_users|length > 0

- name: Read local admins from domain configuration file
  set_fact:
    local_admins: "{{ domain.workstations | selectattr('name', 'equalto', ansible_env.COMPUTERNAME) | map(attribute='local_admins') | reject('undefined') | select() | list }}"

- name: Ensure local administrator users are created
  ansible.windows.win_group_membership:
    name: Administrators
    members: "{{ item }}"
  with_items: "{{ local_admins }}"
  when: local_admins|length > 0

- name: Read Windows Firewall status from domain configuration file
  set_fact:
    windows_firewall_state: "{{ (domain.enable_windows_firewall is defined and domain.enable_windows_firewall is true) | ternary('enabled', 'disabled') }}"

- name: "Ensure Windows firewall is {{ windows_firewall_state }}"
  community.windows.win_firewall:
    profiles: [Domain, Private, Public]
    state: "{{ windows_firewall_state }}"

# https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-privacy#privacy-disableprivacyexperience
- name: Disable 'Choose your privacy settings' screen at first logon
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\OOBE
    name: DisablePrivacyExperience
    data: "1"
    type: dword
