---
- name: Configure domain controllers
  hosts: domain_controllers
  vars_files: 
   - accansible.yml

  gather_facts: no
  roles:
  - role: domain-controller
  - role: windows-base
  - role: wef-collector
    tags: [ wef ]
  - role: sysmon
    tags: [ sysmon ]
  - role: logging-base
    tags: [ logging-base ]

  vars:
    ansible_user: "{{ ansible.username }}"
    ansible_password: "{{ ansible.password }}"
    