---
- name: Configure workstations
  hosts: workstations
  vars_files: 
   - account_ansible.yml
  gather_facts: no
  roles:
  - domain-member
  - windows-base
  - wef-client
  - sysmon
  - logging-base
  vars:
    ansible_user: "{{ ansible.username }}"
    ansible_password: "{{ ansible.password }}"